version: '3.7'

services:

  # ----- PostgreSQLデータベース -----
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./config/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5050:80"
    depends_on:
      - db

  # ----- Axum (Rust) バックエンド: 雛形 -----
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - cargo-cache:/usr/local/cargo/registry
      - cargo-target:/app/target
    # DB接続情報などをロード
    env_file:
      - ./backend/.env
    environment:
      ENV: local
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: myuser
      DB_PASSWORD: password
      DB_NAME: mydb
    depends_on:
      - db

volumes:
  db-data:
  cargo-cache:
  cargo-target:
