[package]
edition = "2021"
name = "backend"
version = "0.1.0"

[dependencies]
axum = "0.6"
lambda_http = "0.7"
serde = {version = "1.0", features = ["derive"]}
tokio = {version = "1.28", features = ["macros"]}
