name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Docker Compose ビルドを試す例
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker containers
        run: |
          docker compose build
